language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install numpy
  - python setup.py install
before_script:
  - git clone https://github.com/spectralpython/sample-data.git ~/spectral_data
script: SPECTRAL_DATA=~/spectral_data python -m spectral.tests.run
